1. Sendo utilizada independentemente de tecnologia, a modelagem conceitual é essencial para representar de forma abstrata os dados e relacionamento de um domínio de aplicação.
Evita-se a amarração a um tipo especifico de banco de dados ou tecnologia, facilitando mudanças futuras e promovendo a longevidade do sistema, assim como pode servir como meio de comunicação entre desenvolvedores e os usuários, "traduzindo" a estrutura técnica.

2. Entidades fortes possuem chaves primarias proprias e sua existencia independe de outras, entidades fracas não possuem chaves primarias proprias e necessita da entidade forte para existir e é identificada por uma chave parcial combinada a chave da entidade forte. Um exemplo de entidade forte e fraca são  o cadastro de cliente/fornecedor e lançamento financeiro.

3. Uma superchave é qualquer conjunto de atributos que permite identificar unicamente uma tupla em uma tabela. Dentro dessas, uma chave candidata é uma superchave mínima, ou seja, sem atributos redundantes. A chave primária é uma das chaves candidatas escolhida para representar unicamente cada registro na tabela. A escolha correta da chave primária é essencial, pois ela deve ser estável, única, não nula e imutável, garantindo a integridade dos dados e o bom desempenho do sistema.

4. Um relacionamento ternário ocorre quando três entidades estão envolvidas simultaneamente em uma relação que não pode ser representada adequadamente por relacionamentos binários sem perda de significado. Por exemplo, em um sistema de vendas, a relação entre Produto, Fornecedor e Loja pode indicar que um determinado fornecedor fornece um produto específico para uma loja específica, com condições particulares para cada combinação, algo que não seria possível representar corretamente apenas com pares de entidades.

5. Atributos multivalorados são aqueles que podem assumir vários valores para uma mesma entidade, como os telefones de um cliente, e são representados no modelo entidade-relacionamento por um oval com borda dupla; sua normalização geralmente envolve a criação de uma nova entidade para armazenar esses valores separadamente. Já os atributos derivados são calculados a partir de outros atributos, como a idade obtida a partir da data de nascimento, sendo representados por um oval tracejado; nesse caso, é recomendável não armazenar o valor derivado, mas sim calculá-lo quando necessário.
